# Generated by Django 4.0.8 on 2024-04-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationalbot', '0002_usermeta_alter_log_user_alter_step_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='assistant_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='thread_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
