# Generated by Django 4.0.8 on 2024-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationalbot', '0003_log_assistant_id_log_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='state',
            field=models.CharField(choices=[('greeting', 'greeting'), ('question', 'question'), ('end', 'end')], default='greeting', max_length=100, null=True),
        ),
    ]
