# Generated by Django 4.0.8 on 2024-04-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationalbot', '0005_remove_log_assistant_id_remove_log_thread_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='assistant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
