# Generated by Django 4.0.8 on 2024-04-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationalbot', '0006_alter_usermeta_assistant_id_alter_usermeta_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bot_response',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_input',
            field=models.CharField(max_length=1000),
        ),
    ]
