# Generated by Django 4.0.8 on 2024-04-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationalbot', '0007_alter_log_bot_response_alter_log_user_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bot_response',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_input',
            field=models.TextField(),
        ),
    ]
