# Generated by Django 4.0.8 on 2024-04-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversationalbot', '0008_alter_log_bot_response_alter_log_user_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='user',
        ),
        migrations.AddField(
            model_name='step',
            name='user_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conversationalbot.usermeta'),
        ),
    ]
