# Generated by Django 4.0.8 on 2024-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationalbot', '0009_remove_step_user_step_user_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='step',
        ),
        migrations.AddField(
            model_name='log',
            name='state',
            field=models.CharField(choices=[('greeting', 'greeting'), ('question', 'question'), ('end', 'end')], default='greeting', max_length=100, null=True),
        ),
    ]
